defaults:
  - dataset: example
  - policy: srth_original
  - _self_

seed: 1
device: cuda
batch_size: 8
num_workers: 4
num_epochs: 1000
validate_every: 20
save_every: 200
checkpoint_dir: ${hydra:runtime.output_dir}/checkpoints

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
