defaults:
  - dataloader: complete                # Sample dataloader settings for low-level training.
  - policy: diffusion_trans                        # ACT policy architecture and optimizer defaults.
  - override hydra/job_logging: custom # Write logs both to stdout and to the Hydra run dir.
  - _self_

seed: 1          # Global random seed for NumPy / PyTorch / data shuffling.
device: cuda     # Falls back to CPU only if the training code is updated to do so explicitly.

# these will pass to both policy and dataloader cfgs.
# its easier to define them once as they must be consistent
# across policy and dataloader
action_mode: hybrid_relative
ll_history_chunk_size: 0
ll_future_chunk_size: 60


train:
  num_train_steps: 100      # orig is 300000
  num_warmup_steps: 50000
  save_every: 50            # Save a checkpoint every N training steps. orig is 10000
  keep_every: 50000            # Prune checkpoints so only one representative checkpoint survives per bin.
  validate_every: 50         # Run the validation loop every N training steps. orig is 10000
  checkpoint_dir: ${hydra:runtime.output_dir}/checkpoints
  resume_checkpoint: null   # Optional checkpoint path to resume model/optimizer/scheduler state from.
  training_hydra_cfg_path: null # Optional path to the hydra config.yaml file that was used to train the checkpoint

wandb:
  project: diffusion_training             # W&B project name.
  entity: ychadda1-johns-hopkins-university # W&B team / user namespace.
  name: diffusion_test       # Human-readable run name.

  # resume settings
  resume: false        # Set true to restore config state from a previous W&B run.
  id: null             # Required when resuming; optional otherwise.
  mode: online         # online OR offline OR disabled

hydra:
  run:
    # Each run gets its own timestamped directory with logs, configs, and checkpoints.
    dir: outputs/low_level_policy/train/${now:%Y-%m-%d}/${now:%H-%M-%S}
