repo_id: surpass/cholecystectomy_06_30_26

tissue_sample_ids_train:
  [
    Tissue#1,
    Tissue#2,
    Tissue#3,
    Tissue#4,
    Tissue#5,
    Tissue#6,
    Tissue#7,
    Tissue#8,
    Tissue#9,
    Tissue#10,
    Tissue#11,
    Tissue#12,
    Tissue#13,
    Tissue#14,
    Tissue#15,
    Tissue#16,
    Tissue#17,
    Tissue#18,
    Tissue#19,
    Tissue#20,
    Tissue#21,
    Tissue#22,
    Tissue#23,
    Tissue#24,
    Tissue#25,
    Tissue#26,
    Tissue#27,
    Tissue#28,
    # Tissue#29,
    Tissue#30,
  ]
tissue_sample_ids_val: [Tissue#29]
batch_size: 12 # Batch size for both train and validation dataloaders.
num_workers: 16 # DataLoader worker processes.

# this will filter out all data that does not contain annotated keypoints
use_only_kp_annotated_data: False

# inherited parameters
action_mode: ${..action_mode}
history_chunk_size: ${ll_history_chunk_size}
future_chunk_size: ${ll_future_chunk_size}
phases:
  unzipping:
    - 1_grabbing_gallbladder_right
    - 1_grabbing_gallbladder_right_recovery
    - 2_initial_incision
    - 2_initial_incision_recovery
    - 3_hook_to_local_home
    - 4_hook_tissue
    - 4_hook_tissue_recovery
    - 5_cauterize_tissue_right
    - 6_hook_to_global_home
    - 7_grasper_to_home
    - 8_grabbing_gallbladder_left
    - 8_grabbing_gallbladder_left_recovery
    - 9_returning_to_initial_incision
    - 9_returning_to_initial_incision_recovery
    - 10_cauterize_tissue_left
    - 11_regrab
    - 12_hook_to_global_home
    - 13_grasper_to_home
