dataset_dir: /home/grayson/surpass/srth-surpass/raw_data/Cholecystectomy_grasp_only

num_episodes_train: 100
tissue_sample_ids_train: [1]

num_episodes_val: 28
tissue_sample_ids_val: [2]

action_mode: hybrid_relative      # hybrid_relative OR ego OR relative_endoscope
norm_scheme: std                  # std OR min_max
chunk_size: 60
use_language: true
language_encoder: distilbert      # currently only support distilbert

use_auto_label: false             # TODO: No clue what this does. Maybe remove?

batch_size: 12
num_workers: 16
