dataset_dir: /srv/shared_data/Cholecystectomy_processed/Cholecystectomy

tissue_sample_ids_train: [1, 2, 3, 4]
tissue_sample_ids_val: [5]
chunk_size: 60
batch_size: 12                    # Batch size for both train and validation dataloaders.
num_workers: 16                   # DataLoader worker processes.

action_mode: ${train.action_mode}

phases:
  unzipping:
        - 1_grabbing_gallbladder_right
        - 1_grabbing_gallbladder_right_recovery
        - 2_initial_incision
        - 2_initial_incision_recovery
        - 3_hook_to_local_home
        - 4_hook_tissue
        - 4_hook_tissue_recovery
        # - 5_cauterize_tissue_right
        # - 6_hook_to_global_home
        # - 7_grasper_to_home
        # - 8_grabbing_gallbladder_left
        # - 8_grabbing_gallbladder_left_recovery
        # - 9_returning_to_initial_incision
        # - 9_returning_to_initial_incision_recovery
        # - 10_cauterize_tissue_left
        # - 11_regrab
        # - 12_hook_to_global_home
        # - 13_grasper_to_home